"""
FastAPI Dashboard Server - Skill Gap Radar
Serves dashboard and provides API endpoints for resume analysis and market data
"""

from fastapi import FastAPI, WebSocket, UploadFile, File, HTTPException
from fastapi.responses import HTMLResponse, FileResponse, JSONResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import asyncio
import json
import os
import sys
from pathlib import Path
from typing import List, Dict, Optional
from datetime import datetime
import tempfile

# Add parent directories to Python path
sys.path.append(str(Path(__file__).parent.parent))
sys.path.append(str(Path(__file__).parent.parent / "resume_processing"))
sys.path.append(str(Path(__file__).parent.parent / "analysis"))

# Import resume processing and analysis modules
try:
    from resume_processing.resume_parser import ResumeParser
    print("✓ Imported ResumeParser")
except ImportError as e:
    print(f"✗ Error importing ResumeParser: {e}")
    ResumeParser = None

try:
    from analysis.skill_gap import SkillGapAnalyzer
    print("✓ Imported SkillGapAnalyzer")
except ImportError as e:
    print(f"✗ Error importing SkillGapAnalyzer: {e}")
    SkillGapAnalyzer = None

# Initialize FastAPI app
app = FastAPI(
    title="Skill Gap Radar API",
    description="Real-time job market analysis and resume skill gap analyzer",
    version="2.0.0"
)

# WebSocket clients
clients = []

# Store current skill demand data (updated by Spark streaming processor)
current_skill_demand = {}

# Pydantic models
class ResumeAnalysisRequest(BaseModel):
    resume_skills: Optional[List[str]] = None


class SkillGapRequest(BaseModel):
    resume_skills: List[str]


# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ================================================================
# DASHBOARD ROUTES
# ================================================================

@app.get("/", response_class=HTMLResponse)
async def get_dashboard():
    """Serve the main dashboard HTML page"""
    html_path = Path(__file__).parent / "index.html"
    if html_path.exists():
        return FileResponse(html_path)
    else:
        return HTMLResponse("<h1>Dashboard not found</h1><p>index.html missing</p>")


@app.get("/health")
async def health_check():
    """Health check endpoint"""
    return {
        "status": "healthy",
        "timestamp": datetime.now().isoformat(),
        "resume_parser": ResumeParser is not None,
        "skill_analyzer": SkillGapAnalyzer is not None
    }


# ================================================================
# MARKET SKILLS ENDPOINT
# ================================================================

@app.get("/market-skills")
async def get_market_skills(top_n: int = 50):
    """
    Get top demanded skills from the job market
    
    Reads from Parquet files generated by Spark streaming
    
    Args:
        top_n: Number of top skills to return (default: 50)
        
    Returns:
        JSON with top skills and their demand counts
    """
    try:
        import pandas as pd
        from pyspark.sql import SparkSession
        
        parquet_path = Path(__file__).parent.parent / "data" / "processed_jobs" / "skill_demand"
        
        if not parquet_path.exists():
            # Fallback: use in-memory data from streaming processor
            if current_skill_demand:
                sorted_skills = sorted(
                    current_skill_demand.items(),
                    key=lambda x: x[1],
                    reverse=True
                )[:top_n]
                
                return {
                    "skills": [s[0] for s in sorted_skills],
                    "counts": [s[1] for s in sorted_skills],
                    "total": len(sorted_skills),
                    "source": "in-memory",
                    "timestamp": datetime.now().isoformat()
                }
            else:
                return {
                    "skills": [],
                    "counts": [],
                    "total": 0,
                    "source": "none",
                    "message": "No market data available yet. Start the job collector and stream processor.",
                    "timestamp": datetime.now().isoformat()
                }
        
        # Read from Parquet
        spark = SparkSession.builder.appName("MarketSkillsAPI").getOrCreate()
        df = spark.read.parquet(str(parquet_path))
        
        # Aggregate counts by skill (sum all occurrences)
        skill_counts = df.groupBy("skill").sum("count").collect()
        
        # Convert to dictionary and sort
        market_skills = {row.skill: row['sum(count)'] for row in skill_counts}
        sorted_skills = sorted(
            market_skills.items(),
            key=lambda x: x[1],
            reverse=True
        )[:top_n]
        
        spark.stop()
        
        return {
            "skills": [s[0] for s in sorted_skills],
            "counts": [s[1] for s in sorted_skills],
            "total": len(sorted_skills),
            "source": "parquet",
            "timestamp": datetime.now().isoformat()
        }
    
    except Exception as e:
        # Fallback to in-memory data
        if current_skill_demand:
            sorted_skills = sorted(
                current_skill_demand.items(),
                key=lambda x: x[1],
                reverse=True
            )[:top_n]
            
            return {
                "skills": [s[0] for s in sorted_skills],
                "counts": [s[1] for s in sorted_skills],
                "total": len(sorted_skills),
                "source": "in-memory-fallback",
                "error": str(e),
                "timestamp": datetime.now().isoformat()
            }
        else:
            raise HTTPException(
                status_code=503,
                detail=f"Unable to load market skills: {str(e)}"
            )


@app.get("/data")
async def get_dashboard_data():
    """Compatibility endpoint expected by dashboard frontend"""
    market_data = await get_market_skills(top_n=50)
    return {
        "skills": market_data.get("skills", []),
        "counts": market_data.get("counts", []),
    }


# ================================================================
# RESUME ANALYSIS ENDPOINT
# ================================================================

@app.post("/resume-analysis")
async def analyze_resume_endpoint(file: UploadFile = File(...)):
    """
    Analyze resume and compare against market demand
    
    Accepts PDF resume, extracts skills using NLP, and compares against
    current job market demand
    
    Args:
        file: PDF resume file (only PDF accepted)
        
    Returns:
        JSON with extracted skills, market comparison, and gap analysis
    """
    # Validate PDF file
    if not file.filename.lower().endswith('.pdf'):
        raise HTTPException(
            status_code=400,
            detail="Only PDF files are accepted"
        )
    
    if not ResumeParser:
        raise HTTPException(
            status_code=503,
            detail="Resume parser not available. Install required dependencies."
        )
    
    if not SkillGapAnalyzer:
        raise HTTPException(
            status_code=503,
            detail="Skill gap analyzer not available."
        )
    
    try:
        # Save uploaded file temporarily
        with tempfile.NamedTemporaryFile(delete=False, suffix='.pdf') as tmp_file:
            content = await file.read()
            tmp_file.write(content)
            tmp_file_path = tmp_file.name
        
        # Parse resume and extract skills
        parser = ResumeParser()
        result = parser.analyze_resume(tmp_file_path)
        
        # Clean up temp file
        os.unlink(tmp_file_path)
        
        if not result["success"]:
            raise HTTPException(
                status_code=400,
                detail=f"Error parsing resume: {result.get('error', 'Unknown error')}"
            )
        
        resume_skills = result["skills"]
        
        # Get market demand data
        market_data = await get_market_skills(top_n=100)
        
        if not market_data["skills"]:
            return {
                "success": True,
                "file_name": file.filename,
                "resume_skills": resume_skills,
                "skill_count": len(resume_skills),
                "gap_analysis": None,
                "message": "Resume analyzed but no market data available for comparison"
            }
        
        # Build market skills dictionary
        market_skills = dict(zip(market_data["skills"], market_data["counts"]))
        
        # Perform gap analysis
        analyzer = SkillGapAnalyzer(market_skills)
        gap_analysis = analyzer.analyze_gap(resume_skills, top_n=50)
        
        return {
            "success": True,
            "file_name": file.filename,
            "word_count": result["word_count"],
            "resume_skills": resume_skills,
            "skill_count": len(resume_skills),
            "gap_analysis": gap_analysis,
            "timestamp": datetime.now().isoformat()
        }
    
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Error analyzing resume: {str(e)}"
        )


# ================================================================
# WEBSOCKET FOR REAL-TIME UPDATES
# ================================================================

@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    """WebSocket connection for real-time skill demand updates"""
    await websocket.accept()
    clients.append(websocket)
    print(f"✓ Client connected. Total clients: {len(clients)}")
    
    try:
        # Send current data immediately
        if current_skill_demand:
            await websocket.send_json({
                "skills": list(current_skill_demand.keys()),
                "counts": list(current_skill_demand.values())
            })
        
        while True:
            # Keep connection alive
            await websocket.receive_text()
    
    except Exception as e:
        print(f"⚠ Client disconnected: {e}")
    
    finally:
        if websocket in clients:
            clients.remove(websocket)
        print(f"Client removed. Total clients: {len(clients)}")


@app.post("/update")
async def update_skill_demand(data: dict):
    """
    Receive skill demand updates from Spark streaming processor
    and broadcast to connected WebSocket clients
    """
    global current_skill_demand
    
    current_skill_demand = dict(zip(data.get("skills", []), data.get("counts", [])))
    
    # Broadcast to all WebSocket clients
    disconnected_clients = []
    for client in clients:
        try:
            await client.send_json(data)
        except Exception as e:
            print(f"Error sending to client: {e}")
            disconnected_clients.append(client)
    
    # Remove disconnected clients
    for client in disconnected_clients:
        clients.remove(client)
    
    return {"status": "ok", "clients_notified": len(clients)}


# ================================================================
# LEGACY COMPATIBILITY ENDPOINTS
# ================================================================

@app.get("/api/skill_demand")
async def get_skill_demand_legacy():
    """Legacy endpoint for backward compatibility"""
    market_data = await get_market_skills(top_n=50)
    return {
        "skills": market_data["skills"],
        "counts": market_data["counts"],
        "total_skills": market_data["total"],
        "source": market_data["source"]
    }


@app.post("/api/upload_resume")
async def upload_resume_legacy(file: UploadFile = File(...)):
    """Legacy endpoint for resume upload"""
    result = await analyze_resume_endpoint(file)
    resume_skills = result.get("resume_skills", [])
    return {
        "success": result.get("success", False),
        "file_name": result.get("file_name", file.filename),
        "skills": resume_skills,
        "skills_found": len(resume_skills),
        "word_count": result.get("word_count", 0),
        "gap_analysis": result.get("gap_analysis"),
        "timestamp": result.get("timestamp", datetime.now().isoformat()),
    }


@app.post("/api/analyze_gap")
async def analyze_gap_legacy(request: SkillGapRequest):
    """Legacy endpoint expected by dashboard frontend"""
    if not SkillGapAnalyzer:
        raise HTTPException(
            status_code=503,
            detail="Skill gap analyzer not available."
        )

    market_data = await get_market_skills(top_n=100)
    if not market_data.get("skills"):
        raise HTTPException(
            status_code=503,
            detail="No market skill data available yet. Start stream processor first."
        )

    market_skills = dict(zip(market_data["skills"], market_data["counts"]))
    analyzer = SkillGapAnalyzer(market_skills)

    analysis = analyzer.analyze_gap(request.resume_skills, top_n=50)
    recommendations = analyzer.suggest_learning_path(request.resume_skills, max_skills=5)
    skill_score = analyzer.get_skill_match_rate(request.resume_skills)

    return {
        "skill_score": skill_score,
        "match_count": analysis.get("matching_count", 0),
        "gap_count": analysis.get("missing_count", 0),
        "resume_skill_count": analysis.get("resume_skill_count", len(request.resume_skills)),
        "matching_skills": analysis.get("matching_skills", []),
        "missing_skills": analysis.get("missing_skills", []),
        "recommendations": recommendations,
        "overall_assessment": analysis.get("overall_assessment", ""),
    }


# ================================================================
# UTILITY ENDPOINTS
# ================================================================

@app.get("/api/stats")
async def get_statistics():
    """Get system statistics"""
    try:
        from pyspark.sql import SparkSession
        
        spark = SparkSession.builder.appName("StatsAPI").getOrCreate()
        
        # Count jobs in Parquet
        jobs_path = Path(__file__).parent.parent / "data" / "processed_jobs" / "raw_jobs"
        job_count = 0
        
        if jobs_path.exists():
            df = spark.read.parquet(str(jobs_path))
            job_count = df.count()
        
        spark.stop()
        
        return {
            "total_jobs_processed": job_count,
            "total_skills_tracked": len(current_skill_demand),
            "websocket_clients": len(clients),
            "timestamp": datetime.now().isoformat()
        }
    
    except Exception as e:
        return {
            "total_jobs_processed": 0,
            "total_skills_tracked": len(current_skill_demand),
            "websocket_clients": len(clients),
            "error": str(e),
            "timestamp": datetime.now().isoformat()
        }


if __name__ == "__main__":
    import uvicorn
    
    print("\n" + "="*60)
    print("Starting Skill Gap Radar Dashboard Server")
    print("="*60)
    print(f"Resume Parser: {'✓ Available' if ResumeParser else '✗ Not available'}")
    print(f"Skill Analyzer: {'✓ Available' if SkillGapAnalyzer else '✗ Not available'}")
    print(f"Storage: Parquet files (Hive removed)")
    print("="*60)
    print("\nAPI Endpoints:")
    print("  - GET  /market-skills      - Get top demanded skills")
    print("  - POST /resume-analysis    - Analyze resume PDF")
    print("  - GET  /api/stats          - System statistics")
    print("  - WS   /ws                 - Real-time updates")
    print("="*60 + "\n")
    
    uvicorn.run(app, host="0.0.0.0", port=8000)
